### ISSUE TITLE
AWS SDK 2.0 is EOL

### ISSUE THREAD

**Issue by leehambley** [carrierwaveuploader/carrierwave-aws#166]
- https://aws.amazon.com/blogs/developer/deprecation-schedule-for-aws-sdk-for-ruby-v2/

> We are announcing that version 2 of the AWS SDK For Ruby will enter maintenance mode on 11/20/2020. Support for version 2 will end on 11/21/2021. During maintenance mode we will continue to fix bugs and patch security issues until support for version 2 ends, at which point no further updates to version 2 will be released. We encourage customers to upgrade from version 2 to version 3 to continue receiving regular updates.

Probably `carrierwave-aws` needs to be modified to have specific dependencies on the individual AWS services (I'm assuming S3?) that it requires?

**Comment by sorentwo** [comment]
@leehambley Thanks for the notice. This library is lightly maintained and I'll get to the changes when I can. In the meantime, if somebody else is willing and able a PR is welcome.

**Comment by leehambley** [comment]
Hi Parker, maybe I can make time to do this, I'm absolutely unfamiliar with
carrierwave, it's just one of about a hundred gems in an app I work in. Is
there anything except S3 that carrierwave-aws is using?

Lee Hambley
http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by sorentwo** [comment]
@leehambley That would be fantastic. No, it only uses S3. There is optional support for CF, but that's through a signing proc and not a dependency.

**Comment by leehambley** [comment]
Hi @sorentwo I'm back from christmas vacation and wanted to work on this today, but I see spec failures on the master branch under Ruby 2.5.7 and any other version that I tried (I checked .travis.yml to see what you were targeting there)

```
$ bundle exec rake
Running RuboCop...
/home/leehambley/code/stuart/carrierwave-aws/.rubocop.yml: Style/IndentArray has the wrong namespace - should be Layout
Inspecting 18 files
..................

18 files inspected, no offenses detected
/home/leehambley/.asdf/installs/ruby/2.5.7/bin/ruby -I/home/leehambley/code/stuart/carrierwave-aws/.bundle/ruby/2.5.0/gems/rspec-core-3.10.1/lib:/home/leehambley/code/stuart/carrierwave-aws/.bundle/ruby/2.5.0/gems/rspec-support-3.10.1/lib /home/leehambley/code/stuart/carrierwave-aws/.bundle/ruby/2.5.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Run options:
  include {:focus=>true}
  exclude {:type=>:feature}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 6075
........................................F...

Failures:

  1) CarrierWave::Storage::AWSOptions#write_options works if aws_attributes is a Proc
     Failure/Error: expect { options.write_options(file) }.to_not raise_error

       expected no Exception, got #<NoMethodError: undefined method `week' for 1:Integer> with backtrace:
         # ./spec/carrierwave/storage/aws_options_spec.rb:57:in `block (4 levels) in <top (required)>'
         # ./lib/carrierwave/storage/aws_options.rb:45:in `aws_attributes'
         # ./lib/carrierwave/storage/aws_options.rb:23:in `write_options'
         # ./spec/carrierwave/storage/aws_options_spec.rb:60:in `block (4 levels) in <top (required)>'
         # ./spec/carrierwave/storage/aws_options_spec.rb:60:in `block (3 levels) in <top (required)>'
     # ./spec/carrierwave/storage/aws_options_spec.rb:60:in `block (3 levels) in <top (required)>'

Finished in 0.06122 seconds (files took 0.52541 seconds to load)
44 examples, 1 failure

Failed examples:

rspec ./spec/carrierwave/storage/aws_options_spec.rb:55 # CarrierWave::Storage::AWSOptions#write_options works if aws_attributes is a Proc

Randomized with seed 6075

/home/leehambley/.asdf/installs/ruby/2.5.7/bin/ruby -I/home/leehambley/code/stuart/carrierwave-aws/.bundle/ruby/2.5.0/gems/rspec-core-3.10.1/lib:/home/leehambley/code/stuart/carrierwave-aws/.bundle/ruby/2.5.0/gems/rspec-support-3.10.1/lib /home/leehambley/code/stuart/carrierwave-aws/.bundle/ruby/2.5.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

not sure what's going on here, perhaps you'd like to comment before I risk sending a PR on flaky foundations.

Cheers!

**Comment by leehambley** [comment]
This would fix that:

``` ruby
$ GIT_PAGER=cat git diff
diff --git a/spec/carrierwave/storage/aws_options_spec.rb b/spec/carrierwave/storage/aws_options_spec.rb
index e746d13..67354da 100644
--- a/spec/carrierwave/storage/aws_options_spec.rb
+++ b/spec/carrierwave/storage/aws_options_spec.rb
@@ -1,4 +1,5 @@
 require 'spec_helper'
+require 'date'

 describe CarrierWave::Storage::AWSOptions do
   uploader_klass = Class.new do
@@ -54,7 +55,7 @@ describe CarrierWave::Storage::AWSOptions do

     it 'works if aws_attributes is a Proc' do
       expect(uploader).to receive(:aws_attributes).and_return(
-        -> { { expires: 1.week.from_now.httpdate } }
+        -> { { expires: (Date.today + 7).httpdate } }
       )

       expect { options.write_options(file) }.to_not raise_error
```

**Comment by sorentwo** [comment]
Thanks for following up!

This looks like a case of rubocop changing out from under us. That particular change perfectly fine by me 👍

**Comment by leehambley** [comment]
Thanks, so I'll at least send a PR for that low hanging fruit.

The thing that brought me here was the deprecation warnings that I originally reported back in December - but now I see that the gemspec for this project specifies `aws-sdk-s3` already, at `~>1` which is still absolutely fine. Their latest release is 1.87.0 - December 21, 2020 (293 KB)  so that _should_ be fine.

We seem to have something in our own (extensive) app Gemfile pinning a specific version:

```
# Gemfile
39:gem "aws-sdk", "~> 2.11.193", require: nil
40:gem "aws-sdk-resources", "~> 2.11.193", require: nil
```
so I need to look deeper. 

Apologies for the noise.

**Comment by sorentwo** [comment]
No worries! Thanks for looking into it at all.

**Comment by tleish** [comment]
Any updates on this?

**Comment by mshibuya** [comment]
This is ineligible. carrierwave-aws depends on aws-sdk-s3 ~> 1.0, the latest version of which depend on aws-sdk-core 3.
