### ISSUE TITLE
content-type octet-stream issue

### ISSUE THREAD

**Issue by romarioliveira25** [carrierwaveuploader/carrierwave-aws#173]
Hello,

I have experiencing an issue uploading pdf files when sometimes (especially when the file is bigger than 1MB) the content type header is incorrectly set with binary/octet-stream header instead of application/pdf.

This is making it impossible to embed the pdf file at the iframe tag in my application, to workarround it I'm forcing set the correct response header with `url(response_content_type: 'application/pdf')`, but the upload continue creating objects with incorrect content type metadata at the  bucket.

Any know issue related with this situation was reported?

Environment:
carrierwave version 2.2.3
carrierwave-aws version 1.5.0
aws-sdk-s3 version 1.117.2
rails 6.1.7
ruby 2.7.7

**Comment by mshibuya** [comment]
@timross14 But with your way files larger than 100MB will still fail, right?
The solution we need should be to ensure content type being set properly even with a multipart copy.

**Comment by timross14** [comment]
@mshibuya Correct, the ultimate solution would be to fix the underlying content type issue.  Selfishly, we enforce a 100mb upload limit, so this would do the trick for us, but I can do a little digging to see if I can track down the core issue when I have some bandwidth. 

The contribution I have ready just introduces the configuration option, which seems like an easy win and makes the way this works a bit more transparent.

**Comment by bgwilson87** [comment]
I'm running into this same problem, I submitted an issue to aws-sdk-ruby. https://github.com/aws/aws-sdk-ruby/issues/2821

My project also enforces an upload limit, so I'm able to use the @timross14 workaround for now.

**Comment by mshibuya** [comment]
Fixed by https://github.com/aws/aws-sdk-ruby/pull/2822.
