### ISSUE TITLE
Ready to CarrierWave 3.0?

### ISSUE THREAD

**Issue by issei-m** [carrierwaveuploader/carrierwave-aws#176]
CarrierWave 3.0 is officially [GA](https://github.com/carrierwaveuploader/carrierwave/releases/tag/v3.0.0) now, so I suppose this gem is also ready for the next release (maybe 1.6.0?).

Do you have plans to do it? 

Thanks!

**Comment by krasnoukhov** [comment]
Same question here!

**Comment by mshibuya** [comment]
Just released 1.6.0.
